Script started on 廿十八年六月十九日 (週二) 十三時46分52秒
]0;pd2vm@pd2-vbox: ~/lab8[01;32mpd2vm@pd2-vbox[00m:[01;34m~/lab8[00m$ make
g++ -c tetris.cpp
g++ -c genMino.cpp
g++ -c MinoI.cpp
g++ -c MinoS.cpp
g++ -c MinoL.cpp
g++ -c MinoA.cpp
g++ -c MinoB.cpp
g++ -c Mino.cpp
g++ -o lab8 tetris.o genMino.o MinoI.o MinoS.o MinoL.o MinoA.o MinoB.o Mino.o
]0;pd2vm@pd2-vbox: ~/lab8[01;32mpd2vm@pd2-vbox[00m:[01;34m~/lab8[00m$ ./lab8
 get to try
 get to try
 get to try
 get to try
 get to try
]0;pd2vm@pd2-vbox: ~/lab8[01;32mpd2vm@pd2-vbox[00m:[01;34m~/lab8[00m$ exit

Script done on 廿十八年六月十九日 (週二) 十三時47分十秒
